### ISSUE TITLE
Write detail about the project in Readme.md

### ISSUE THREAD

**Issue by jhabarsingh** [jhabarsingh/XRAY-Covid-Prediction#1]
In this project are creating  Django Rest Api which takes chest X-RAY image of the patient as an input and predict weather the patient is corona positive or not.

You can add these details in the README.md file. Using  diagrams/images would be appreciated

**Comment by maddsic** [comment]
okay seen!

**Comment by maddsic** [comment]
can you assign this to me!

**Comment by jhabarsingh** [comment]
okay Sure
